### ISSUE TITLE
Utility method is misspelled : suffle => shuffle

### ISSUE THREAD

**Issue by Tzaphkiel** [s-yadav/jsonQ#14]
*suffle*
suffle the element and return a new array of suffled elements.
Syntax : jsonQ.suffle(array) 
Return : array - suffled array .
Parameters
array : Array which you want to suffle.

The method should be written as follows: [shuffle](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=define+shuffle)

**Comment by JCOvergaar** [comment]
It's pretty sad that I found this a year and a half later while googling to figure out what the hell "suffle" was supposed to do within that same, unchanged code.

**Comment by s-yadav** [comment]
Missed to go through issues of this module. Will fix this. Thanks.
