### ISSUE TITLE
ReferenceError: jsonQ is not defined

### ISSUE THREAD

**Issue by davidnewcomb** [s-yadav/jsonQ#18]
According to your documentation this should work, but I just get `ReferenceError: jsonQ is not defined`.
What do I need to add so I can use it?

```
<html>
<head>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://raw.githubusercontent.com/s-yadav/jsonQ/master/jsonQ.min.js"></script>
</head>
<body>
<script>
alert('script');
$(document).ready(function () {
	alert('ready');
	var jsonObj = { "name": "David"};
	var name = jsonQ(jsonObj).find("name").value();
	alert('working-name='+name);
}
);
</script>
</body>
</html>
```

**Comment by s-yadav** [comment]
This is a bundling issue. I will fix this.

**Comment by davidnewcomb** [comment]
Is this coming soon?

**Comment by s-yadav** [comment]
Ohh sorry I didn't saw the initial comments properly and thought I had made some changes on build for this package which was the case for some other package.  

There is nothing wrong on the build. 
The url you are using jsonQ is incorrect. That url has `plain/text` mime type. Use this url instead`https://cdn.rawgit.com/s-yadav/jsonQ/master/jsonQ.min.js`
