### ISSUE TITLE
"window is not defined"

### ISSUE THREAD

**Issue by JulianKingman** [s-yadav/jsonQ#3]
Can jsonQ run on a node server? It seems based on this error that it's a client-only script...

```
W20151112-11:53:14.218(-5)? (STDERR) ReferenceError: window is not defined
W20151112-11:53:14.218(-5)? (STDERR)     at lib/jsonQ.min.js:9:1
```

**Comment by s-yadav** [comment]
Yes, You have to use node version of jsonQ, You should install jsonQ using

```
npm install jsonq 
```

or add on package.json of your project .

**Comment by JulianKingman** [comment]
If I do that, won't I have to use browserify to get it to work on the client-side? Sorry if it's a stupid question, I'm rather new to node.

**Comment by s-yadav** [comment]
Ohh, I got your case. I have replaced hardcoded window object to global object, so it will support all platform. You can try with the latest build .

**Comment by JulianKingman** [comment]
Cool, thanks!
