### ISSUE TITLE
jsonQ.js ==>  module.exports = jsonQ; module is not defined..

### ISSUE THREAD

**Issue by roshan-0409** [s-yadav/jsonQ#5]
Hi,

I am trying to run exactly same code as in sample example . when i try to run i got error at module.exports=jsonQ stating module is not defined in jsonQ.js file..Please let me know if i am missing anything..

**Comment by s-yadav** [comment]
Are you trying to use node js version of jsonq

**Comment by roshan-0409** [comment]
Yes.. but later i just copied raw js which has version 1.0.4 then it works but npm pulls only 1.0.3 version..
