### ISSUE TITLE
name.path is not a function jsonQ

### ISSUE THREAD

**Issue by felipexbenevides** [s-yadav/jsonQ#8]
i have a problem,

name.path is not a function jsonQ

![1](https://cloud.githubusercontent.com/assets/12820399/15451592/456678f6-1fa1-11e6-84e5-e2979ef91c51.PNG)
![2](https://cloud.githubusercontent.com/assets/12820399/15451593/456e3ef6-1fa1-11e6-8335-c43bae36c8d7.PNG)

**Comment by s-yadav** [comment]
declaring name variable in global scope, treat the value as name of window, so it tries to typecast any thing in string. So why when you do 
```js
var name = family.find('name') //in global space
//name is '[object Object]' as a string
```
If you try same thing inside a function it will work.
Try 
```js
(function(){
  var family = jsonQ(jsonObj),
       name = family.find('name');
 
   console.log(name.path())
}())
```
Read http://stackoverflow.com/questions/20945498/var-name-produces-strange-result-in-javascript 

---
I will update the docs as it is misleading.
